StudentInformationSystem/Areas/Teacher/Controllers/TeacherQualificationController.cs
using Microsoft.EntityFrameworkCore;
using StudentInformationSystem.Areas.Base;
using StudentInformationSystem.Areas.Teacher.Models;
using StudentInformationSystem.Common;
using StudentInformationSystem.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace StudentInformationSystem.Areas.Teacher.Controllers
{
    public class TeacherQualificationController : BaseController
    {
        public ActionResult Index()
        {
            return View(new TeacherVM());
        }

        public ActionResult QualificationIndex(int? id)
        {
            ViewBag.IsToEdit = id > 0;

            if ((id ?? 0) == 0)
                return PartialView("_QualificationIndex", new List<TeacherQualificationVM>());

            var teacher = db.Teachers.Where(x => x.Id == id).FirstOrDefault();
            if (teacher == null)
                return HttpNotFound();
            var obj = new TeacherVM(teacher);

            ViewBag.TeacherId = obj.Id;
            return PartialView("_QualificationIndex", obj.Qualifications);
        }

        public ActionResult QualificationCreate(int? teacherId)
        {
            if ((teacherId ?? 0) == 0)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var ent = db.Teachers.Find(teacherId);

            if (ent == null)
                return HttpNotFound();

            var vm = new TeacherQualificationVM() { TeacherId = ent.Id, AwardedYear = DateTime.Now.Year };
            return PartialView("_QualificationCreate", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult QualificationCreate(TeacherQualificationVM vm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var obj = db.Teachers.Find(vm.TeacherId);

                    vm.CreatedBy = this.GetCurrUser();
                    vm.CreatedDate = DateTime.Now;
                    obj.TeacherQualifications.Add(vm.GetEntity());

                    db.SaveChanges();

                    AddAlert(AlertStyles.success, "Teacher Qualification Added Successfully.");
                    string url = Url.Action("QualificationIndex", new { id = vm.TeacherId });
                    return Json(new { success = true, url });
                }
            }
            catch (DbEntityValidationException dbEx)
            { this.ShowEntityErrors(dbEx); }
            catch (Exception ex)
            { AddAlert(AlertStyles.danger, ex.GetInnerException().Message); }

            return PartialView("_QualificationCreate", vm);
        }

        public ActionResult QualificationEdit(int? id)
        {
            if ((id ?? 0) == 0)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var ent = db.TeacherQualifications.Find(id);

            if (ent == null)
                return HttpNotFound();

            var vm = new TeacherQualificationVM(ent);
            return PartialView("_QualificationEdit", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult QualificationEdit(TeacherQualificationVM vm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var obj = db.TeacherQualifications.Find(vm.Id);
                    vm.CopyContent(obj, "QualificationType,Institute,AwardedYear,Remarks");
                    obj.ModifiedBy = this.GetCurrUser();
                    obj.ModifiedDate = DateTime.Now;

                    db.SaveChanges();

                    AddAlert(AlertStyles.success, "Teacher Qualification Modified Successfully.");
                    string url = Url.Action("QualificationIndex", new { id = obj.TeacherId });
                    return Json(new { success = true, url });
                }
            }
            catch (DbEntityValidationException dbEx)
            { this.ShowEntityErrors(dbEx); }
            catch (Exception ex)
            { AddAlert(AlertStyles.danger, ex.GetInnerException().Message); }

            return PartialView("_QualificationEdit", vm);
        }

        [HttpPost, ActionName("QualificationDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult QualificationDeleteConfirmed(int id)
        {
            string msg = string.Empty;
            var teacherId = 0;

            try
            {
                var obj = db.TeacherQualifications.Find(id);
                if (obj == null)
                { throw new DbUpdateConcurrencyException(""); }

                teacherId = obj.TeacherId;
                var entry = db.Entry(obj);
                entry.State = EntityState.Unchanged;
                entry.Collection(x => x.TeacherQualificationSubjects).Load();
                db.TeacherQualificationSubjects.RemoveRange(entry.Entity.TeacherQualificationSubjects);
                entry.State = EntityState.Deleted;
                db.SaveChanges();

                AddAlert(AlertStyles.success, "Teacher Qualification Deleted Successfully.");
            }
            catch (Exception ex)
            {
                msg = ex.GetInnerException().Message;
                AddAlert(AlertStyles.danger, msg);
            }

            string url = "";
            if (msg.IsBlank())
            { url = Url.Action("QualificationIndex", new { id = teacherId }); }
            return Json(new { success = true, url, hdrData = "", msg });
        }

        public ActionResult SubjectIndex(int? id)
        {
            ViewBag.IsToEdit = id > 0;

            if ((id ?? 0) == 0)
                return PartialView("_SubjectIndex", new List<TeacherQualificationSubjectVM>());

            var qlf = db.TeacherQualifications.Where(x => x.Id == id).FirstOrDefault();
            if (qlf == null)
                return HttpNotFound();
            var obj = new TeacherQualificationVM(qlf);

            ViewBag.TeacherQualificationId = obj.Id;
            return PartialView("_SubjectIndex", obj.QualificationSubjects);
        }

        public ActionResult SubjectCreate(int? TeacherQualificationId)
        {
            if ((TeacherQualificationId ?? 0) == 0)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var ent = db.TeacherQualifications.Find(TeacherQualificationId);

            if (ent == null)
                return HttpNotFound();

            var vm = new TeacherQualificationSubjectVM() { TeacherQualificationId = ent.Id };
            return PartialView("_SubjectCreate", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubjectCreate(TeacherQualificationSubjectVM vm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var obj = db.TeacherQualifications.Find(vm.TeacherQualificationId);

                    vm.CreatedBy = this.GetCurrUser();
                    vm.CreatedDate = DateTime.Now;
                    obj.TeacherQualificationSubjects.Add(vm.GetEntity());

                    db.SaveChanges();

                    AddAlert(AlertStyles.success, "Teacher Qualification Subject Added Successfully.");
                    string url = Url.Action("SubjectIndex", new { id = vm.TeacherQualificationId });
                    return Json(new { success = true, url, hdrData = "" });
                }
            }
            catch (DbEntityValidationException dbEx)
            { this.ShowEntityErrors(dbEx); }
            catch (Exception ex)
            { AddAlert(AlertStyles.danger, ex.GetInnerException().Message); }

            return PartialView("_SubjectCreate", vm);
        }

        [HttpPost, ActionName("SubjectDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult SubjectDeleteConfirmed(int id)
        {
            string msg = string.Empty;
            var teacherQualificationId = 0;

            try
            {
                var obj = db.TeacherQualificationSubjects.Find(id);
                if (obj == null)
                { throw new DbUpdateConcurrencyException(""); }

                teacherQualificationId = obj.TeacherQualificationId;
                var entry = db.Entry(obj);
                entry.State = EntityState.Deleted;
                db.SaveChanges();

                AddAlert(AlertStyles.success, "Teacher Qualification Subject Deleted Successfully.");
            }
            catch (Exception ex)
            {
                msg = ex.GetInnerException().Message;
                AddAlert(AlertStyles.danger, msg);
            }

            string url = "";
            if (msg.IsBlank())
            { url = Url.Action("SubjectIndex", new { id = teacherQualificationId }); }
            return Json(new { success = true, url, hdrData = "", msg });
        }
    }
}

StudentInformationSystem/Areas/Teacher/Views/TeacherQualification/Index.cshtml
@model StudentInformationSystem.Areas.Teacher.Models.TeacherVM

@{
    ViewBag.Title = "Teacher Qualifications";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.PopUpSelectorFor(model => model.Id, "Base", "Data", "GetTeachers", new { @class = "form-control" }, "Please select a teacher", null, dspFormat: "{1}", hiddenIndices: "0")
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}

<div id="ChildContent" class="ChildContent" data-local-binding-fn="QualificationsGridBinder">
    @{ Html.RenderAction("QualificationIndex", new { id = Model.Id }); }
</div>

@section Scripts {
    <script src="~/Scripts/Teacher/Qualification.js"></script>
}

StudentInformationSystem/Areas/Teacher/Views/TeacherQualification/_QualificationCreate.cshtml
@model StudentInformationSystem.Areas.Teacher.Models.TeacherQualificationVM

@{ Html.RenderPartial("~/Areas/Base/Views/Shared/_PartialAlert.cshtml"); }

@using (Html.BeginForm())
{
    <br />
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.TeacherId)

        <div class="form-group">
            @Html.LabelFor(model => model.QualificationType, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EnumEditorFor(model => model.QualificationType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.QualificationType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Institute, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Institute, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Institute, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AwardedYear, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.AwardedYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AwardedYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.TextAreaFor(model => model.Remarks, 3, 2, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />
        <div class="pull-right">
            <p>
                <div class="btn-toolbar">
                    <input type="submit" value="Save" class="btn btn-primary" style="min-width:75px" />
                    <input type="button" value="Cancel" class="btn btn-default" style="min-width:75px" />
                </div>
            </p>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentInformationSystem/Areas/Teacher/Views/TeacherQualification/_QualificationEdit.cshtml
@model StudentInformationSystem.Areas.Teacher.Models.TeacherQualificationVM

@{ Html.RenderPartial("~/Areas/Base/Views/Shared/_PartialAlert.cshtml"); }

@using (Html.BeginForm())
{
    <br />
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.TeacherId)

        <div class="form-group">
            @Html.LabelFor(model => model.QualificationType, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EnumEditorFor(model => model.QualificationType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.QualificationType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Institute, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Institute, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Institute, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AwardedYear, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.AwardedYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AwardedYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.TextAreaFor(model => model.Remarks, 3, 2, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />
        <div class="pull-right">
            <p>
                <div class="btn-toolbar">
                    <input type="submit" value="Save" class="btn btn-primary" style="min-width:75px" />
                    <input type="button" value="Cancel" class="btn btn-default" style="min-width:75px" />
                </div>
            </p>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentInformationSystem/Areas/Teacher/Views/TeacherQualification/_QualificationIndex.cshtml
@using System.Linq
@model IEnumerable<StudentInformationSystem.Areas.Teacher.Models.TeacherQualificationVM>

<br />
<h3>Qualifications</h3>

<table id="tblQualifications" style="width:100%;margin-bottom:5px;">
    <thead>
        <tr>
            <th>
                <table class="table table-striped" style="margin: 0;">
                    <thead>
                        <tr>
                            @if (Model.Any())
                            {
                                <th class="btn-3" style="width:5%">
                                </th>
                            }
                            <th style="width:15%">
                                @Html.DisplayNameFor(model => model.QualificationType)
                            </th>
                            <th style="width:25%">
                                @Html.DisplayNameFor(model => model.Institute)
                            </th>
                            <th style="width:10%">
                                @Html.DisplayNameFor(model => model.AwardedYear)
                            </th>
                            <th style="width:30%">
                                @Html.DisplayNameFor(model => model.Remarks)
                            </th>
                            @{
                                if (ViewBag.IsToEdit)
                                {
                                    <th style="width:15%">
                                        @Html.NoEncodeActionLink("<span class='fa fa-plus' style='color:white'></span>", "Add", "QualificationCreate", routeValues: new { teacherId = ViewBag.TeacherId }, htmlAttributes: new { data_popup_editor = "", @class = "btn btn-primary float-right btn-sm", data_title = "Add Teacher Qualification" })
                                    </th>
                                }
                            }
                        </tr>
                    </thead>
                </table>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr data-pid="@item.Id">
                <td id="subject">
                    @Html.HiddenFor(modelItem => item.Id)
                    <div>
                        <table class="table table-striped" style="margin: 0;">
                            <tbody>
                                <tr>
                                    <td class="btn-3" style="width:5%">
                                        <button type="button" name="toggleLecturers" class="btn btn-default btn-sm" aria-label="Left Align" data-subject-id="@item.Id" data-to-edit="@ViewBag.IsToEdit">
                                            <span class="bi bi-chevron-down" aria-hidden="true"></span>
                                        </button>
                                    </td>
                                    <td style="width:15%">
                                        @Html.DisplayFor(modelItem => item.QualificationType)
                                    </td>
                                    <td style="width:25%">
                                        @Html.DisplayFor(modelItem => item.Institute)
                                    </td>
                                    <td style="width:10%">
                                        @Html.DisplayFor(modelItem => item.AwardedYear)
                                    </td>
                                    <td style="width:30%">
                                        @Html.DisplayFor(modelItem => item.Remarks)
                                    </td>
                                    @{
                                        if (ViewBag.IsToEdit)
                                        {
                                            <td class="btn-2" style="width:15%">
                                                <div class="d-grid gap-2 d-md-block pull-right">
                                                    @using (Html.BeginForm("QualificationDelete", "TeacherQualification", new { id = item.Id }))
                                                    {
                                                        @Html.AntiForgeryToken()
                                                        @Html.NoEncodeActionLink("<span class='bi bi-pencil' style='color:black'></span>", "Edit", "QualificationEdit", routeValues: new { id = item.Id }, htmlAttributes: new { data_popup_editor = "", @class = "btn btn-warning btn-sm", data_title = "Edit Teacher Qualification" })                                                        
                                                        @Html.ConfirmSubmitButton("<span class='bi bi-trash'></span>", "Are you sure you want to delete?", "Confirm teacher qualification deletion", "<span class='bi bi-trash'></span> Delete", new { data_popup_delete = "", @class = "btn btn-danger btn-sm" })
                                                    }
                                                </div>
                                            </td>
                                        }
                                    }
                                </tr>
                            </tbody>
                        </table>

                        <div name="lecDiv" class="ChildContent" style="width: 75%; margin-left: auto; margin-right: auto;display:none;">

                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

@if (ViewBag.IsToEdit)
{
    Html.RenderPartial("~/Areas/Base/Views/Shared/_PartialAlert.cshtml");
}

StudentInformationSystem/Areas/Teacher/Views/TeacherQualification/_SubjectCreate.cshtml
@model StudentInformationSystem.Areas.Teacher.Models.TeacherQualificationSubjectVM

@{ Html.RenderPartial("~/Areas/Base/Views/Shared/_PartialAlert.cshtml"); }

@using (Html.BeginForm())
{
    <br />
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.TeacherQualificationId)

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectId, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.PopUpSelectorFor(model => model.SubjectId, "Base", "Data", "GetSubjects", new { @class = "form-control" }, "Please select a Subject", null, dspFormat: "{1}", hiddenIndices: "0")
                @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />
        <div class="pull-right">
            <p>
                <div class="btn-toolbar">
                    <input type="submit" value="Save" class="btn btn-primary" style="min-width:75px" />
                    <input type="button" value="Cancel" class="btn btn-default" style="min-width:75px" />
                </div>
            </p>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentInformationSystem/Areas/Teacher/Views/TeacherQualification/_SubjectIndex.cshtml
@model IEnumerable<StudentInformationSystem.Areas.Teacher.Models.TeacherQualificationSubjectVM>

<h4>Qualification Subjects</h4>

<table id="tblLecturers" class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SectionName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubjectName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubjectMedium)
            </th>
            @if (ViewBag.IsToEdit)
            {
                <th class="btn-2">
                    @Html.NoEncodeActionLink("<span class='fa fa-plus' style='color:white'></span>", "Add", "SubjectCreate", routeValues: new { TeacherQualificationId = ViewBag.TeacherQualificationId }, htmlAttributes: new { data_popup_editor = "", @class = "btn btn-primary pull-right btn-sm", data_title = "Add Qualification Subject" })
                </th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr data-pid="@item.Id">
                <td>
                    @Html.DisplayFor(modelItem => item.SectionName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SubjectName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SubjectMedium)
                </td>
                @if (ViewBag.IsToEdit)
                {
                    <td class="btn-1">
                        <div class="pull-right">
                            @using (Html.BeginForm("SubjectDelete", "TeacherQualification", new { id = item.Id }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ConfirmSubmitButton("<span class='bi bi-trash'></span>", "Are you sure you want to delete?", "Confirm subject deletion",
                                    "<span class='bi bi-trash'></span> Delete", new { data_popup_delete = "", @class = "btn btn-danger btn-sm" })
                            }
                        </div>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

@if (ViewBag.IsToEdit)
{
    Html.RenderPartial("~/Areas/Base/Views/Shared/_PartialAlert.cshtml");
}