StudentInformationSystem/Areas/Admin/Controllers/UserPermissionController.cs
using Microsoft.EntityFrameworkCore;
using StudentInformationSystem.Data;
using StudentInformationSystem.Data.Models;
using StudentInformationSystem.Areas.Admin.Models;
using StudentInformationSystem.Areas.Base;
using StudentInformationSystem.Common;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace StudentInformationSystem.Areas.Admin.Controllers
{
    [ExtendedAuthorize(Roles = PermissionConstants.AdminUser)]
    public class UserPermissionController : BaseController
    {
        public ActionResult Index(BaseViewModel<PermissionVM> vm)
        {
            vm.SetList(db.Permissions.AsQueryable(), "Name");
            return View(vm);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Permission permission = db.Permissions.Find(id);
            if (permission == null)
            {
                return HttpNotFound();
            }
            return View(new PermissionVM(permission));
        }

        public ActionResult Create()
        {
            var vm = new PermissionVM();
            Session[sskCrtdObj] = vm;
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PermissionVM permission)
        {
            try
            {
                if (permission.Name == null )
                { ModelState.AddModelError("Name", "Name field is required"); }
                if (permission.Code == null)
                { ModelState.AddModelError("Code", "Code field is required"); }

                if (ModelState.IsValid)
                {
                    permission.CreatedBy = this.GetCurrUser();
                    permission.CreatedDate = DateTime.Now;
                    var obj = db.Permissions.Add(permission.GetEntity()).Entity;

                    var mnuLst = permission.MenusJson.DeserializeJson<List<int>>();

                    foreach (var det in mnuLst)
                    {
                        obj.PermissionMenuAccesses.Add(new PermissionMenuAccess() { PermissionId = obj.PermissionId, MenuId = det });
                    }

                    var grdLst = permission.GradesJson.DeserializeJson<List<int>>();

                    foreach (var det in grdLst)
                    {
                        obj.PermissionGradeAccesses.Add(new PermissionGradeAccess() { PermissionId = obj.PermissionId, GradeId = det });
                    }

                    db.SaveChanges();

                    AddAlert(AlertStyles.success, "User permission created successfully.");
                    return RedirectToAction("Index");
                }
            }
            catch (DbEntityValidationException dbEx)
            { this.ShowEntityErrors(dbEx); }
            catch (Exception ex)
            { AddAlert(AlertStyles.danger, ex.GetInnerException().Message); }

            return View(permission);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Permission permission = db.Permissions.Find(id);
            if (permission == null)
            {
                return HttpNotFound();
            }
            var obj = new PermissionVM(permission);
            Session[sskCrtdObj] = obj;
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PermissionVM permission)
        {
            byte[] curRowVersion = null;
            try
            {
                if (ModelState.IsValid)
                {
                    var svm = (PermissionVM)Session[sskCrtdObj];

                    var obj = db.Permissions.Find(permission.PermissionId);
                    if (obj == null)
                    { throw new DbUpdateConcurrencyException(); }

                    curRowVersion = obj.RowVersion;
                    var modObj = permission.GetEntity();
                    var props = "Name";
                    modObj.CopyContent(obj, props);

                    obj.ModifiedBy = this.GetCurrUser();
                    obj.ModifiedDate = DateTime.Now;

                    db.Entry(obj).OriginalValues["RowVersion"] = permission.RowVersion;

                    var mnuLst = permission.MenusJson.DeserializeJson<List<int>>();

                    db.PermissionMenuAccesses.RemoveRange(obj.PermissionMenuAccesses.Where(x => !mnuLst.Contains(x.MenuId)));
                    mnuLst = mnuLst.Except(obj.PermissionMenuAccesses.Select(x => x.MenuId)).ToList();
                    foreach (var det in mnuLst)
                    {
                        obj.PermissionMenuAccesses.Add(new PermissionMenuAccess() { PermissionId = obj.PermissionId, MenuId = det });
                    }

                    var grdLst = permission.GradesJson.DeserializeJson<List<int>>();

                    db.PermissionGradeAccesses.RemoveRange(obj.PermissionGradeAccesses.Where(x => !grdLst.Contains(x.GradeId)));
                    grdLst = grdLst.Except(obj.PermissionGradeAccesses.Select(x => x.GradeId)).ToList();
                    foreach (var det in grdLst)
                    {
                        obj.PermissionGradeAccesses.Add(new PermissionGradeAccess() { PermissionId = obj.PermissionId, GradeId = det });
                    }

                    db.SaveChanges();

                    AddAlert(AlertStyles.success, "User Permission modified successfully.");
                    return RedirectToAction("Index");
                }
            }
            catch (DbUpdateConcurrencyException ex)
            {
                this.ShowConcurrencyErrors(ex);
                permission.RowVersion = curRowVersion;
            }
            catch (DbEntityValidationException dbEx)
            { this.ShowEntityErrors(dbEx); }
            catch (Exception ex)
            { AddAlert(AlertStyles.danger, ex.GetInnerException().Message); }

            return View(permission);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(PermissionVM permission)
        {
            try
            {
                var obj = db.Permissions.Find(permission.PermissionId);
                if (obj == null)
                { throw new DbUpdateConcurrencyException(""); }
                db.Detach(obj);
                
                var entry = db.Entry(permission.GetEntity());
                entry.State = EntityState.Unchanged;
                entry.Collection(x => x.PermissionMenuAccesses).Load();
                db.PermissionMenuAccesses.RemoveRange(entry.Entity.PermissionMenuAccesses);
                entry.Collection(x => x.PermissionGradeAccesses).Load();
                db.PermissionGradeAccesses.RemoveRange(entry.Entity.PermissionGradeAccesses);
                entry.State = EntityState.Deleted;
                db.SaveChanges();

                AddAlert(AlertStyles.success, "User Permission deleted successfully.");
                return RedirectToAction("Index");
            }
            catch (DbUpdateConcurrencyException ex)
            {
                this.ShowConcurrencyErrors(ex, true);
                if (ex.Message == "")
                { return RedirectToAction("Index"); }
            }
            catch (Exception ex)
            {
                AddAlert(AlertStyles.danger, ex.GetInnerException().Message);
            }
            return RedirectToAction("Details", new { id = permission.PermissionId });
        }

        public ActionResult ChildIndex(int? id, bool isToEdit = false)
        {
            PermissionVM obj;

            if (isToEdit && Session[sskCrtdObj] is PermissionVM)
            { obj = (PermissionVM)Session[sskCrtdObj]; }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Permission permission = db.Permissions.Where(x => x.PermissionId == id).FirstOrDefault();
                if (permission == null)
                {
                    return HttpNotFound();
                }
                obj = new PermissionVM(permission);
            }

            ViewBag.IsToEdit = isToEdit;
            ViewBag.PermissionID = obj.PermissionId;
            return PartialView("_ChildIndex", obj.MenusList);
        }

        public ActionResult GradeIndex(int? id, bool isToEdit = false)
        {
            PermissionVM obj;

            if (isToEdit && Session[sskCrtdObj] is PermissionVM)
            { obj = (PermissionVM)Session[sskCrtdObj]; }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Permission permission = db.Permissions.Where(x => x.PermissionId == id).FirstOrDefault();
                if (permission == null)
                {
                    return HttpNotFound();
                }
                obj = new PermissionVM(permission);
            }
            var gradesList = db.Grades.ToList();

            ViewBag.IsToEdit = isToEdit;
            ViewBag.PermissionID = obj.PermissionId;
            return PartialView("_GradeIndex", gradesList);
        }
    }
}

StudentInformationSystem/Areas/Admin/Views/UserPermission/Create.cshtml
@model StudentInformationSystem.Areas.Admin.Models.PermissionVM

@{
    ViewBag.Title = "Create User Permission";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <p>
            <input id="btnSave" type="submit" value="Save" class="btn btn-primary" style="min-width:75px" />
        </p>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MenusJson)
        @Html.HiddenFor(model => model.GradesJson)

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}

<div class="row">
    <div class="ChildContent col-md-6">
        @{ Html.RenderAction("ChildIndex", new { id = Model.PermissionId, isToEdit = true }); }
    </div>
    <div class="ChildContent col-md-6">
        @{ Html.RenderAction("GradeIndex", new { id = Model.PermissionId, isToEdit = true }); }
    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/admin/userpermission")
}

StudentInformationSystem/Areas/Admin/Views/UserPermission/Details.cshtml
@model StudentInformationSystem.Areas.Admin.Models.PermissionVM

@{
    ViewBag.Title = "User Permission Details";
}

<div>
    <hr />
    @using (Html.BeginForm("Delete", "UserPermission"))
    {
        @Html.HiddenFor(model => model.PermissionId)
        @Html.HiddenFor(model => model.RowVersion)
        @Html.HiddenFor(model => model.MenusJson)
        @Html.HiddenFor(model => model.GradesJson)
        @Html.AntiForgeryToken()
        <p>
            <div class="btn-toolbar">
                @Html.ActionLink("Edit", "Edit", new { id = Model.PermissionId }, new { @class = "btn btn-primary", style = "min-width:75px" })
                @Html.ConfirmSubmitButton("Delete", "Are you sure you want to delete?", "Confirm user permission deletion",
                 "<span class='glyphicon glyphicon-trash'></span> Delete", new { @class = "btn btn-danger", style = "min-width:75px" })
            </div>
        </p>
    }

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DetailsViewFor(model => model.Code)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DetailsViewFor(model => model.Name)
            </div>
        </div>
    </div>
</div>



<div class="row">
    <div class="ChildContent col-md-6">
        @{ Html.RenderAction("ChildIndex", new { id = Model.PermissionId }); }
    </div>
    <div class="ChildContent col-md-6">
        @{ Html.RenderAction("GradeIndex", new { id = Model.PermissionId }); }
    </div>
</div>

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

@section Scripts {
    @Scripts.Render("~/bundles/admin/userpermission")
}

StudentInformationSystem/Areas/Admin/Views/UserPermission/Edit.cshtml
@model StudentInformationSystem.Areas.Admin.Models.PermissionVM

@{
    ViewBag.Title = "Edit User Permission";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <p>
            <input id="btnSave" type="submit" value="Save" class="btn btn-primary" style="min-width:75px" />
        </p>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PermissionId)
        @Html.HiddenFor(model => model.RowVersion)
        @Html.HiddenFor(model => model.MenusJson)
        @Html.HiddenFor(model => model.GradesJson)

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}

<div class="row">
    <div class="ChildContent col-md-6">
        @{ Html.RenderAction("ChildIndex", new { id = Model.PermissionId, isToEdit = true }); }
    </div>
    <div class="ChildContent col-md-6">
        @{ Html.RenderAction("GradeIndex", new { id = Model.PermissionId, isToEdit = true }); }
    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/admin/userpermission")
}

StudentInformationSystem/Areas/Admin/Views/UserPermission/Index.cshtml
@model StudentInformationSystem.Common.BaseViewModel<StudentInformationSystem.Areas.Admin.Models.PermissionVM>

@{
    ViewBag.Title = "User Permissions";
    var grid = Model.GetGrid();
}

@{
    var srchOpts = new List<SelectListItem>();
    srchOpts.Add(new SelectListItem { Text = "Permission Name", Value = "Name" });
}

<p>
    @Html.ActionLink("Create", "Create", null, new { @class = "btn btn-primary", style = "min-width:75px" })
</p>

@using (Html.BeginForm("Index", null, FormMethod.Get))
{
    @Html.HiddenFor(model => model.FilterBy, new { Value = "Name" });
    <div class="form-horizontal row">
        <div class="form-inline">
            <div class="col-md-6">
                @Html.EditorFor(model => model.Filter, new { htmlAttributes = new { @class = "form-control" } })
                <input type="submit" value="Search" name="Search" class="btn btn-default" />
            </div>
        </div>
    </div>

    <hr />

    <div id="content">
        @grid.GetHtml(
        tableStyle: "mGrid no-foot",
        mode: WebGridPagerModes.All,
        columns: grid.Columns(
            grid.Column(null, null, format: (item) => Html.NoEncodeActionLink("<span class='glyphicon glyphicon-eye-open' style='color:black'></span>", "View Details", "Details", routeValues: new { id = item.PermissionID }, htmlAttributes: new { @class = "btn btn-warning btn-xs" }), style: "btn-1"),
            grid.SortColumn(columnName: "Code", header: "Permission Code"),
            grid.SortColumn(columnName: "Name", header: "Permission Name")))

        <div id="content-footer">
            @grid.PagerList(WebGridPagerModes.All, Model.PageSize, Model.TotalRecords)
        </div>
    </div>
}

StudentInformationSystem/Areas/Admin/Views/UserPermission/_ChildIndex.cshtml
@model List<StudentInformationSystem.Data.Models.Menu>

<style type="text/css">
    ul.tree, ul.tree ul {
        list-style-type: none;
        background: url(/Content/Images/vline.png) repeat-y;
        margin: 0;
        padding: 0;
    }

        ul.tree ul {
            margin-left: 10px;
        }

        ul.tree li {
            margin: 5px 0 5px 0;
            padding: 0 12px;
            line-height: 20px;
            background: url(/Content/Images/node.png) no-repeat;
            color: #369;
            font-weight: bold;
        }

            ul.tree li:last-child {
                background: #f5f5f5 url(/Content/Images/lastnode.png) no-repeat;
            }

        ul.tree span.glyphicon {
            cursor: pointer;
        }
</style>

<hr />
<h3>Menus</h3>

<p>
    <div class="btn-toolbar">
        <button id="btnExpAll" type="button" class="btn btn-default">Expand All</button>
        <button id="btnColapsAll" type="button" class="btn btn-default">Collapse All</button>
        @if (ViewBag.IsToEdit)
        {
            <button id="btnCheckAll" type="button" class="btn btn-default">Check All</button>
            <button id="btnUnchkAll" type="button" class="btn btn-default">Uncheck All</button>
        }
    </div>
</p>

@{
    var lstMenus = Html.GetAllMenus();
}

@helper IterateMenus(List<StudentInformationSystem.Data.Models.Menu> FullList, int? menuID)
{
var lst = FullList.Where(x => x.ParentMenuId == menuID).OrderBy(x => x.DisplaySeq).ToList();

foreach (var item in lst)
{
    if (item.Type == "I")
    {
            <li data-menu-id="@item.MenuId"><span class="glyphicon glyphicon-unchecked" aria-hidden="true"></span> @item.Text</li>
    }
    else if (item.Type == "D")
    {
            <li data-menu-id="@item.MenuId"><span class="glyphicon glyphicon-unchecked" aria-hidden="true"></span> ----- Divider -----</li>
    }
    else if (item.Type == "M")
    {
            <li data-menu-id="@item.MenuId">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <span class="glyphicon glyphicon-unchecked" aria-hidden="true"></span> @item.Text
                <ul style="display:none">
                    @IterateMenus(FullList, item.MenuId)
                </ul>
            </li>
    }
}
}

<div>
    <ul class="tree" id="tree_menu">
        @{
            @IterateMenus(lstMenus, null)
        }
    </ul>
</div>

@if (ViewBag.IsToEdit)
{
    Html.RenderPartial("~/Areas/Base/Views/Shared/_PartialAlert.cshtml");
}