StudentInformationSystem/Areas/Academic/Controllers/SubjectController.cs
using Microsoft.EntityFrameworkCore;
using StudentInformationSystem.Data;
using StudentInformationSystem.Data.Models;
using StudentInformationSystem.Areas.Academic.Models;
using StudentInformationSystem.Areas.Base;
using StudentInformationSystem.Common;
using System;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Linq;

namespace StudentInformationSystem.Areas.Academic.Controllers
{
    public class SubjectController : BaseController
    {
        public ActionResult Index(BaseViewModel<SubjectVM> vm)
        {
            vm.SetList(db.Subjects.AsQueryable(), "Code");
            return View(vm);
        }
        public ActionResult Create()
        {
            var subject = new SubjectVM();

            return View(subject);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SubjectVM subject)
        {
            try
            {
                var exName = db.Subjects.Where(e => e.SectionId == subject.SectionId && e.SubjectCategoryId == subject.SubjectCategoryId && e.Medium == subject.Medium && e.Code.ToLower().Trim() == subject.Code.ToLower().Trim()).FirstOrDefault();
                if (exName != null)
                { ModelState.AddModelError("", "Subject Code Already Exists for the selected Section, Category & Medium."); }

                exName = db.Subjects.Where(e => e.SectionId == subject.SectionId && e.SubjectCategoryId == subject.SubjectCategoryId && e.Medium == subject.Medium && e.Number == subject.Number).FirstOrDefault();
                if (exName != null)
                { ModelState.AddModelError("", "Subject Number Already Exists for the selected Section, Category & Medium."); }

                if (ModelState.IsValid)
                {
                    subject.CreatedBy = this.GetCurrUser();
                    subject.CreatedDate = DateTime.Now;
                    db.Subjects.Add(subject.GetEntity());
                    db.SaveChanges();

                    AddAlert(AlertStyles.success, "Subject Information created successfully.");
                    return RedirectToAction("Index");
                }
            }
            catch (DbEntityValidationException dbEx)
            { this.ShowEntityErrors(dbEx); }
            catch (Exception ex)
            { AddAlert(AlertStyles.danger, ex.GetInnerException().Message); }

            return View(subject);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject clibs = db.Subjects.Find(id);
            if (clibs == null)
            {
                return HttpNotFound();
            }
            return View(new SubjectVM(clibs));
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subjects.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(new SubjectVM(subject));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SubjectVM subject)
        {
            byte[] curRowVersion = null;
            try
            {
                var exName = db.Subjects.Where(e => e.Id != subject.Id && e.SectionId == subject.SectionId && e.SubjectCategoryId == subject.SubjectCategoryId && e.Medium == subject.Medium && e.Code.ToLower().Trim() == subject.Code.ToLower().Trim()).FirstOrDefault();
                if (exName != null)
                { ModelState.AddModelError("", "Subject Code Already Exists for the selected Section, Category & Medium."); }

                exName = db.Subjects.Where(e => e.Id != subject.Id && e.SectionId == subject.SectionId && e.SubjectCategoryId == subject.SubjectCategoryId && e.Medium == subject.Medium && e.Number == subject.Number).FirstOrDefault();
                if (exName != null)
                { ModelState.AddModelError("", "Subject Number Already Exists for the selected Section, Category & Medium."); }

                if (ModelState.IsValid)
                {
                    var obj = db.Subjects.Find(subject.Id);
                    if (obj == null)
                    { throw new DbUpdateConcurrencyException(); }

                    curRowVersion = obj.RowVersion;
                    var modObj = subject.GetEntity();
                    modObj.CopyContent(obj, "SectionId,SubjectCategoryId,Code,Number,Medium,Description");

                    obj.ModifiedBy = this.GetCurrUser();
                    obj.ModifiedDate = DateTime.Now;

                    db.Entry(obj).OriginalValues["RowVersion"] = subject.RowVersion;
                    db.SaveChanges();

                    AddAlert(AlertStyles.success, "Subject Information modified successfully.");
                    return RedirectToAction("Index");
                }
            }
            catch (DbUpdateConcurrencyException ex)
            {
                this.ShowConcurrencyErrors(ex);
                subject.RowVersion = curRowVersion;
            }
            catch (DbEntityValidationException dbEx)
            { this.ShowEntityErrors(dbEx); }
            catch (Exception ex)
            { AddAlert(AlertStyles.danger, ex.GetInnerException().Message); }

            return View(subject);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(SubjectVM subject)
        {
            try
            {
                var obj = db.Subjects.Find(subject.Id);
                if (obj == null)
                { throw new DbUpdateConcurrencyException(""); }
                db.Detach(obj);

                db.Entry(subject.GetEntity()).State = EntityState.Deleted;
                db.SaveChanges();

                AddAlert(AlertStyles.success, "Subject Information deleted successfully.");
                return RedirectToAction("Index");
            }
            catch (DbUpdateConcurrencyException ex)
            {
                this.ShowConcurrencyErrors(ex, true);
                if (ex.Message == "")
                { return RedirectToAction("Index"); }
            }
            catch (Exception ex)
            {
                AddAlert(AlertStyles.danger, ex.GetInnerException().Message);
            }
            return RedirectToAction("Details", new { id = subject.Id });
        }
    }
}

StudentInformationSystem/Areas/Academic/Views/Subject/Create.cshtml
@using StudentInformationSystem.Data.Models;
@model StudentInformationSystem.Areas.Academic.Models.SubjectVM

@{
    ViewBag.Title = "Create Subject";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <p>
            <input type="submit" value="Save" class="btn btn-primary" style="min-width:75px" />
        </p>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SectionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.SelectListFor(model => model.SectionId, (Section x) => x.Id, (Section x) => x.Code, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SectionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectCategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.SelectListFor(model => model.SubjectCategoryId, (SubjectCategory x) => x.Id, (SubjectCategory x) => x.Code, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Medium, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EnumEditorFor(model => model.Medium, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Medium, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}

<br />
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentInformationSystem/Areas/Academic/Views/Subject/Details.cshtml
@model StudentInformationSystem.Areas.Academic.Models.SubjectVM

@{
    ViewBag.Title = "Subject Details";
}

<div>
    <hr />
    @using (Html.BeginForm("Delete", "Subject"))
    {
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.RowVersion)
        @Html.AntiForgeryToken()
        <p>
            <div class="btn-toolbar">
                @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary", style = "min-width:75px" })
                @Html.ConfirmSubmitButton("Delete", "Are you sure you want to delete?", "Confirm subject deletion",
                 "<span class='glyphicon glyphicon-trash'></span> Delete", new { @class = "btn btn-danger", style = "min-width:75px" })
            </div>
        </p>
    }
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DetailsViewFor(model => model.Code)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DetailsViewFor(model => model.Number)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.SectionName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DetailsViewFor(model => model.SectionName)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DetailsViewFor(model => model.CategoryName)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Medium, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DetailsViewFor(model => model.Medium)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DetailsViewFor(model => model.Description)
            </div>
        </div>
        <br />
    </div>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

StudentInformationSystem/Areas/Academic/Views/Subject/Edit.cshtml
@using StudentInformationSystem.Data.Models;
@model StudentInformationSystem.Areas.Academic.Models.SubjectVM

@{
    ViewBag.Title = "Edit Subject";
}

@using (Html.BeginForm())
{

    @Html.HiddenFor(x => x.Id)
    @Html.HiddenFor(x => x.RowVersion)
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <p>
            <input type="submit" value="Save" class="btn btn-primary" style="min-width:75px" />
        </p>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SectionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.SelectListFor(model => model.SectionId, (Section x) => x.Id, (Section x) => x.Code, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SectionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectCategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.SelectListFor(model => model.SubjectCategoryId, (SubjectCategory x) => x.Id, (SubjectCategory x) => x.Code, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Medium, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EnumEditorFor(model => model.Medium, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Medium, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}

<br />
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentInformationSystem/Areas/Academic/Views/Subject/Index.cshtml
@model StudentInformationSystem.Common.BaseViewModel<StudentInformationSystem.Areas.Academic.Models.SubjectVM>

@{
    ViewBag.Title = "Subject Information";
    var grid = Model.GetGrid();
}

@{
    var srchOpts = new List<SelectListItem>();
    srchOpts.Add(new SelectListItem { Text = "Subject", Value = "Code" });
}

<p>
    @Html.ActionLink("Create", "Create", null, new { @class = "btn btn-primary", style = "min-width:75px" })
</p>

@using (Html.BeginForm("Index", null, FormMethod.Get))
{
    <div class="form-horizontal row">
        <div class="col-md-4">
            <div class="form-group">
                @Html.Label("Search By", htmlAttributes: new { @class = "control-label col-md-3", style = "white-space: nowrap;" })
                <div class="col-md-9">
                    @Html.DropDownList("FilterBy", new SelectList(srchOpts, "Value", "Text"), htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.Filter, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <input type="submit" value="Search" name="Search" class="btn btn-default" />
        </div>
    </div>
    <hr />

    <div id="content">
        @grid.GetHtml(
        tableStyle: "mGrid no-foot",
        mode: WebGridPagerModes.All,
        columns: grid.Columns(
            grid.Column(null, null, format: (item) => Html.NoEncodeActionLink("<span class='glyphicon glyphicon-eye-open' style='color:black'></span>", "View Details", "Details", routeValues: new { id = item.Id }, htmlAttributes: new { @class = "btn btn-warning btn-xs" }), style: "btn-1"),
            grid.SortColumn(columnName: "Code", header: "Subject"),
            grid.SortColumn(columnName: "Number", header: "Subject Number"),
            grid.SortColumn(columnName: "CategoryName", header: "Subject Category"),
            grid.SortColumn(columnName: "SectionName", header: "Section"),
            grid.SortColumn(columnName: "Medium", header: "Medium", format: (item) => ((Enum)item.Medium).ToEnumChar()),
            grid.SortColumn(columnName: "Description", header: "Description")))

        <div id="content-footer">
            @grid.PagerList(WebGridPagerModes.All, Model.PageSize, Model.TotalRecords)
        </div>
    </div>
}